version: '3.8'

services:
  db:
    image: postgres:17
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      # POSTGRES_USER 默认就是 postgres，可省略
      # POSTGRES_DB 默认就是 postgres，可省略
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # 只有当你有初始化 SQL 脚本时才需要下面这行
      # - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: my-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./tmp:/usr/share/nginx/tmp
    restart: always
    networks:
      - app-network

  redis:
    image: redis:7.0-alpine
    container_name: my-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - app-network

volumes:
  # ✅ 删除了 mysql-data
  redis_data:
    driver: local
  postgres_data:

networks:
  app-network:
    driver: bridge