spring:
  application:
    name: cheems-ai-code
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cheems-ai-code
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379
      ttl: 3600
  session:
    store-type: redis
    time-to-live: 2592000

server:
  port: 8123
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000



# springdoc-openapi????
springdoc:
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.cheems.cheemsaicode.controller
# knife4j???????????????
knife4j:
  enable: true
  setting:
    language: zh_cn