spring:
  application:
    name: cheems-ai-code
  profiles:
    active: local
  datasource:
    driver-class-name:  org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cheems-ai-code
    username: postgres
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379
      ttl: 3600
  session:
    store-type: redis
    time-to-live: 2592000

server:
  port: 8123
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000

# 腾讯云对象存储配置
cos:
  client:
    host:
    secretId:
    secretKey:
    bucket:
    region:

langchain4j:
  open-ai:
    chat-model:
      api-key: 
      base-url: 
      model-name: 
      log-requests:  true
      log-responses: true
    streaming-chat-model:
      api-key: 
      base-url: 
      model-name: 
      log-requests: true
      log-responses: true
    
# springdoc-openapi????
springdoc:
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.cheems.cheemsaicode.controller
# knife4j???????????????
knife4j:
  enable: true
  setting:
    language: zh_cn